SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `migrations`;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `migrations`;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `migrations`;

-- Create Migrations Table
CREATE TABLE IF NOT EXISTS migrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) UNIQUE NOT NULL,
    status ENUM('pending', 'completed', 'failed') DEFAULT 'pending',
    error_message TEXT,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=1;